//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel24Eq5.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class ARRIVE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARRIVE()
        {
            this.DEPART = new ObservableCollection <DEPART>();
            this.TRX = new ObservableCollection <TRX>();
        }
    
        public int Id_Arrive { get; set; }
        public Nullable<int> Id_Reserve { get; set; }
        public Nullable<int> Id_Client { get; set; }
        public Nullable<System.DateTime> Date_Arrive { get; set; }
        public Nullable<int> Id_Chambre { get; set; }
        public string Recu_Par { get; set; }
    
        public virtual CHAMBRE CHAMBRE { get; set; }
        public virtual CLIENT CLIENT { get; set; }
        public virtual RESERVE RESERVE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<DEPART> DEPART { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<TRX> TRX { get; set; }
    }
}
