//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel24Eq5.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class CHAMBRE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHAMBRE()
        {
            this.ARRIVE = new ObservableCollection <ARRIVE>();
            this.AYANT = new ObservableCollection <AYANT>();
            this.DE = new ObservableCollection <DE>();
        }
    
        public int Id_Chambre { get; set; }
        public Nullable<int> Etage { get; set; }
        public Nullable<decimal> Prix { get; set; }
        //attention bit dans bd fait un bool
        public Nullable<bool> Etat { get; set; }
        public string Code_TypeChambre { get; set; }
        public string Code_Localisation { get; set; }
        public string Memo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<ARRIVE> ARRIVE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<AYANT> AYANT { get; set; }
        public virtual LOCALISATION LOCALISATION { get; set; }
        public virtual TYPECHAMBRE TYPECHAMBRE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<DE> DE { get; set; }
    }
}
