//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel24
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class DEPART
    {
        public int Id_Depart { get; set; }
        public Nullable<int> Id_Arrive { get; set; }
        public Nullable<System.DateTime> Date_Depart { get; set; }
        public string Conf_Par { get; set; }
    
        public virtual ARRIVE ARRIVE { get; set; }
    }
}
