//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel24Eq5.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class RESERVE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESERVE()
        {
            this.ARRIVE = new ObservableCollection <ARRIVE>();
            this.DE = new ObservableCollection <DE>();
        }
    
        public int Id_Reserve { get; set; }
        public Nullable<int> Id_Client { get; set; }
        public Nullable<System.DateTime> Date_Reserve { get; set; }
        public Nullable<System.DateTime> Date_Debut { get; set; }
        public Nullable<System.DateTime> Date_Fin { get; set; }
        public Nullable<bool> Confirme { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<ARRIVE> ARRIVE { get; set; }
        public virtual CLIENT CLIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<DE> DE { get; set; }
    }
}
