//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel24Eq5.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class TRX
    {
        public int Id_Trx { get; set; }
        public Nullable<int> Id_Arrive { get; set; }
        public Nullable<System.DateTime> Date_Trx { get; set; }
        public string Code_TypeTrx { get; set; }
        public Nullable<decimal> Montant { get; set; }
        public string Conf_Par { get; set; }
        public Nullable<bool> Reportee { get; set; }
    
        public virtual ARRIVE ARRIVE { get; set; }
        public virtual TYPETRX TYPETRX { get; set; }
    }
}
