//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel24
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class TYPECHAMBRE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TYPECHAMBRE()
        {
            this.CHAMBRE = new ObservableCollection <CHAMBRE>();
        }
    
        public string Code_TypeChambre { get; set; }
        public string Description { get; set; }
        public Nullable<int> Nbr_Dispo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<CHAMBRE> CHAMBRE { get; set; }
    }
}
